"""Deterministic funny tree names (Heroku/Docker-style word pairs + tree puns)."""

import random

RANDOM_SEED = 42

PRESERVE_TREE_NAMES = frozenset({"Berta"})

ADJECTIVES = [
    "Thirsty",
    "Mighty",
    "Sleepy",
    "Chonky",
    "Dramatic",
    "Wise",
    "Sassy",
    "Mossy",
    "Shady",
    "Breezy",
    "Grumpy",
    "Cheery",
    "Humble",
    "Lucky",
    "Rowdy",
    "Zen",
    "Clumsy",
    "Fancy",
    "Groovy",
    "Jolly",
    "Nervous",
    "Plucky",
    "Quirky",
    "Rusty",
    "Snarky",
    "Tipsy",
    "Wobbly",
    "Zesty",
    "Brooding",
    "Delighted",
    "Feisty",
    "Giggly",
    "Honorable",
    "Impish",
    "Jaded",
    "Kooky",
    "Lofty",
    "Mellow",
    "Noble",
    "Ornery",
]

NOUNS = [
    "Bark Twain",
    "Sir Sapling",
    "Leaf Erickson",
    "Spruce Springsteen",
    "Timberlake",
    "Oakley",
    "Maple McTreeface",
    "Pine Min",
    "Willow Smith",
    "Birch Obama",
    "Professor Birch",
    "Captain Bark",
    "Lady Larch",
    "Count Sapula",
    "Duke of Elm",
    "Baron von Beech",
    "Root Beer",
    "Needle Nixon",
    "Conifer Claus",
    "Acorn Wallace",
    "Twiggy Stardust",
    "Photosynthesis Phil",
    "Chlorophyll Charlie",
    "Sap Queen",
    "Ringo Redwood",
    "Paul McCartree",
    "John Lemon",
    "George Harshison",
    "Bark Obama",
    "Root Downey Jr",
    "Meryl Leaf",
    "Keanu Leaves",
    "Tree Diddy",
    "Snoop Log",
    "Branch Manager",
    "Soil Sister",
    "Mulch Malone",
    "Compost Malone",
    "Shade Thrower",
    "Canopy Khan",
    "Stump Thump",
    "Groot Jr",
    "Fernando",
    "Hedgehog Holmes",
    "Lumberjack Sparrow",
    "Petal Peterson",
    "Barkley",
    "Woody Harrelson",
    "Cedar Murphy",
    "Aspen Kutcher",
]


def funny_tree_name(external_id: int) -> str:
    """Stable, idempotent display name from the geoportal object id."""
    rng = random.Random(external_id ^ RANDOM_SEED)
    return f"{rng.choice(ADJECTIVES)} {rng.choice(NOUNS)}"
